"""adding customer_names to tickets

Revision ID: 0a946c743757
Revises: 53734df5ceeb
Create Date: 2026-07-06 17:00:25.674446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a946c743757'
down_revision: Union[str, Sequence[str], None] = '53734df5ceeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('customer_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_tickets_customer_name'), 'tickets', ['customer_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_customer_name'), table_name='tickets')
    op.drop_column('tickets', 'customer_name')
    # ### end Alembic commands ###
