"""nps tables

Revision ID: 100ceb4d4509
Revises: b43cb292d875
Create Date: 2026-07-08 18:27:00.421737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '100ceb4d4509'
down_revision: Union[str, Sequence[str], None] = 'b43cb292d875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nps_responses',
    sa.Column('response_id', sa.String(), nullable=False),
    sa.Column('end_user_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('excluded_from_calculations', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_index(op.f('ix_nps_responses_created_at'), 'nps_responses', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nps_responses_created_at'), table_name='nps_responses')
    op.drop_table('nps_responses')
    # ### end Alembic commands ###
