"""cursor

Revision ID: 17f952d5b6c6
Revises: be3fa0d61399
Create Date: 2026-07-03 15:20:30.901598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f952d5b6c6'
down_revision: Union[str, Sequence[str], None] = 'be3fa0d61399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_cursors',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.add_column('tickets', sa.Column('owner_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'owner_name')
    op.drop_table('sync_cursors')
    # ### end Alembic commands ###
