"""adds slack channel column

Revision ID: 28a600e7d4b2
Revises: 82d64f2e87a4
Create Date: 2026-07-16 12:46:10.329114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a600e7d4b2'
down_revision: Union[str, Sequence[str], None] = '82d64f2e87a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('slack_channel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'slack_channel')
    # ### end Alembic commands ###
