"""adding csat responses

Revision ID: 302111b177a3
Revises: 0a946c743757
Create Date: 2026-07-07 11:33:54.129864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302111b177a3'
down_revision: Union[str, Sequence[str], None] = '0a946c743757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csat_responses',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('ticket_id', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index(op.f('ix_csat_responses_submitted_at'), 'csat_responses', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_csat_responses_ticket_id'), 'csat_responses', ['ticket_id'], unique=False)
    op.drop_column('tickets', 'csat_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('csat_rating', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_csat_responses_ticket_id'), table_name='csat_responses')
    op.drop_index(op.f('ix_csat_responses_submitted_at'), table_name='csat_responses')
    op.drop_table('csat_responses')
    # ### end Alembic commands ###
