"""adds other_event_name to tickets table

Revision ID: 383cf4a26332
Revises: 4cc676feeb65
Create Date: 2026-08-07 18:16:52.290292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383cf4a26332'
down_revision: Union[str, Sequence[str], None] = '4cc676feeb65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('other_event_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'other_event_name')
    # ### end Alembic commands ###
