"""event_names

Revision ID: 4cc676feeb65
Revises: 71b1d59d661f
Create Date: 2026-08-07 17:51:08.947946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc676feeb65'
down_revision: Union[str, Sequence[str], None] = '71b1d59d661f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('event_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_tickets_event_name'), 'tickets', ['event_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_event_name'), table_name='tickets')
    op.drop_column('tickets', 'event_name')
    # ### end Alembic commands ###
