"""slack workflow names

Revision ID: 82d64f2e87a4
Revises: 100ceb4d4509
Create Date: 2026-07-09 10:30:19.033737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d64f2e87a4'
down_revision: Union[str, Sequence[str], None] = '100ceb4d4509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('slack_workflow', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'slack_workflow')
    # ### end Alembic commands ###
