"""additions to tickets table

Revision ID: 9bfd61e0ecaa
Revises: 17f952d5b6c6
Create Date: 2026-07-04 15:45:53.445765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bfd61e0ecaa'
down_revision: Union[str, Sequence[str], None] = '17f952d5b6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('sub_category', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('owner_assigned_at', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('sla_met', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('final_resolution', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('resolution_bucket', sa.String(), nullable=False))
    op.add_column('tickets', sa.Column('actionable', sa.Boolean(), nullable=False))
    op.add_column('tickets', sa.Column('fcr', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('backline_engineer', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('backline_path', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('jira_link', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('time_to_close_hours', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('time_to_first_agent_reply_hours', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('time_to_first_rep_assignment_hours', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('stage_timings', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_tickets_backline_engineer'), 'tickets', ['backline_engineer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_backline_engineer'), table_name='tickets')
    op.drop_column('tickets', 'stage_timings')
    op.drop_column('tickets', 'time_to_first_rep_assignment_hours')
    op.drop_column('tickets', 'time_to_first_agent_reply_hours')
    op.drop_column('tickets', 'time_to_close_hours')
    op.drop_column('tickets', 'jira_link')
    op.drop_column('tickets', 'backline_path')
    op.drop_column('tickets', 'backline_engineer')
    op.drop_column('tickets', 'fcr')
    op.drop_column('tickets', 'actionable')
    op.drop_column('tickets', 'resolution_bucket')
    op.drop_column('tickets', 'final_resolution')
    op.drop_column('tickets', 'sla_met')
    op.drop_column('tickets', 'owner_assigned_at')
    op.drop_column('tickets', 'sub_category')
    # ### end Alembic commands ###
