"""adds is_holiday to agent shifts

Revision ID: a3d857f0ee05
Revises: 11e50055090c
Create Date: 2026-09-22 19:39:48.566975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d857f0ee05'
down_revision: Union[str, Sequence[str], None] = '11e50055090c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so the ALTER succeeds against the already-seeded rows;
    # matches the ORM's client-side default=False for every future insert.
    op.add_column(
        'agent_shifts',
        sa.Column('is_holiday', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_shifts', 'is_holiday')
    # ### end Alembic commands ###
