"""adds resource source row

Revision ID: a7fdb68bfa31
Revises: 28a600e7d4b2
Create Date: 2026-08-04 17:14:09.722926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7fdb68bfa31'
down_revision: Union[str, Sequence[str], None] = '28a600e7d4b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('record_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'record_source')
    # ### end Alembic commands ###
