"""adds reporter contact name

Revision ID: b43cb292d875
Revises: d947b6a9c753
Create Date: 2026-07-07 13:54:06.229476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43cb292d875'
down_revision: Union[str, Sequence[str], None] = 'd947b6a9c753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('reporter_contact_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'reporter_contact_name')
    # ### end Alembic commands ###
