"""initial table

Revision ID: be3fa0d61399
Revises: 
Create Date: 2026-07-03 14:58:21.089728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be3fa0d61399'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('pipeline_label', sa.String(), nullable=False),
    sa.Column('stage_id', sa.String(), nullable=False),
    sa.Column('stage_label', sa.String(), nullable=False),
    sa.Column('canonical_status', sa.String(), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('primary_category', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('derived_priority', sa.String(), nullable=False),
    sa.Column('priority_inferred', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('sla_first_response_status', sa.String(), nullable=True),
    sa.Column('sla_close_status', sa.String(), nullable=True),
    sa.Column('csat_rating', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_last_modified_at'), 'tickets', ['last_modified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_last_modified_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
