"""adds module in ticket table

Revision ID: d947b6a9c753
Revises: 302111b177a3
Create Date: 2026-07-07 12:56:42.693357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd947b6a9c753'
down_revision: Union[str, Sequence[str], None] = '302111b177a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('hubspot_module', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'hubspot_module')
    # ### end Alembic commands ###
